### ISSUE TITLE
Verify CommandFactory commands carryPosition deployHighCommand

### ISSUE THREAD

**Issue by mandrews281** [entech281/Robot2023#110]
These commands trigger the Gripper.  Are they being used?  
Mechanical/DriveTeam generally don't want to open/close claw unnecessarily, and CarryPosition closes claw at the end.  deployHigh opens the claw; but watching drive team they are generally wanting to make sure the robot is lined up right before opening the claw.

**Comment by dcowden** [comment]
i bet they are not. i noticed several duplicates last night-- including versions with constants not in robotconstants

**Comment by mandrews281** [comment]
I check.  carryPosition is being used (I think it's on the operator panel dial) but deployHigh is not.

**Comment by dcowden** [comment]
ok yeah. we can clean this up
