### ISSUE TITLE
Discuss adding Telemetry data capture to robot

### ISSUE THREAD

**Issue by mandrews281** [entech281/Robot2023#125]
See:
https://docs.wpilib.org/en/stable/docs/software/telemetry/datalog.html

The default behavior is we add DataLogManager.start() to robotInit is to capture the NetworkTables data to a datalog file that gets written to an inserted USB stick (or stored on the robot).  There is a DataLogTool for converting the file into CSV.  This could be ideal for robot diagnostics after the match.

**Comment by dcowden** [comment]
I think we would couple this with downloading and installing this:

https://github.com/Mechanical-Advantage/AdvantageScope

which can read/play the data, on the driver station, and 

and also the gradlew task to download the data  files.

this would be a very powerful addition that would be very nice to get into and tested tonight, before we freeze the code for Anderson qualifier.

**Comment by dcowden** [comment]
Another note: the implications of this are HUGE.  being able to see what operators actually DO, vs what they SAY they do, or remember, is very , very important.  This type of data is essential to making effective battlefield changes and decisions!

**Comment by dcowden** [comment]
The actual to-do item here is to add this code:

```
// Starts recording to data log
DataLogManager.start();

// Record both DS control and joystick data
DriverStation.startDataLog(DataLogManager.getLog());
```

into Robot.java inside of robotInit

**Comment by dcowden** [comment]
we need to test this tonight by putting a usb stick on the rio and seeing if we can read it!
