### ISSUE TITLE
Consider updating the Rio to the latest firmware

### ISSUE THREAD

**Issue by mandrews281** [entech281/Robot2023#126]
The DriveStation software upgrade included an update RoboRio image.  FIRST team update 16 says:

The update also contains roboRIO image version 2023_v3.2 which contains Network Tables stability fixes for LabVIEW teams; C++\Java teams do not need to update to the new image (though there is no harm in doing so).

Do we want to update?

**Comment by dcowden** [comment]
we looked there doesnt appear to be anything that helps us in this firmward version

**Comment by mandrews281** [comment]
OK decision to NOT upgrade.  Closing issue.
