### ISSUE TITLE
PRIORITY #2: Add reliability to autonomous using pneumatic brake

### ISSUE THREAD

**Issue by dcowden** [entech281/Robot2023#188]
The brake will be pneumatic-actuated.

Tasks are as follows:

- [ ] Create Brake Subsystem, using similar pattern to Gripper
- [ ] create command to deploy brake
- [ ] Create command  and button on joystick to deploy and release brake
- [ ] modify auto commands to deploy brake immediately when gyro angle hits a given angle and then gets to nearly flat

**Comment by mandrews281** [comment]
Done
