### ISSUE TITLE
create versions of auto that use a cube vs a cone

### ISSUE THREAD

**Issue by dcowden** [entech281/Robot2023#200]
occasionally we switch based on what other teams are doing

**Comment by mandrews281** [comment]
This should only make a difference in the outer scoring grids (center shouldn't matter),  It will require just a bit of lateral movement to clear charging station and that lateral movement direction (left/right) will depend on which of the two sides of the coopertition grid we are on.  So this is actually TWO new autonomous routines.

**Comment by dcowden** [comment]
coding change is to move slightly sideways on outer move:

- [ ] create auto right and auto left
- [ ] change these to add a sideways move to right or left immediately after scoring
