### ISSUE TITLE
Label driver  joystick buttons

### ISSUE THREAD

**Issue by dcowden** [entech281/Robot2023#214]
We don't want confusion , and especialy we dont want a situation where if we need a backup driver, the driver has to learn all the buttons without a reference! at a minimum, we need a two column sheet with number and function.

**Comment by John-Molfneter** [comment]
Trigger = Togle Turn
Thumb Button = Auto Align
Thumb Pad Bottom Left = Nuge Yaw Left
Thumb Pad Bottom Right = Nuge Yaw Right
Button Pad Top Left = Brake/Coast Toggle
Button Pad Bottom Left = Precision Drive
Button Pad Top Middle = Zero Robot Angle
Button Pad Bottom Middle = Zero Gyro Angle
Button Pad Top Right = Field Absolute
Button Pad Bottom Right = Auto Yaw

**Comment by dcowden** [comment]
can you include the button numbers for each of these? they rae labelled on the joystick. eample: zer gyro is button 9 i think

**Comment by mandrews281** [comment]
Partial labels (base buttons)
