### ISSUE TITLE
Add logic to center autonomous for charging station balance

### ISSUE THREAD

**Issue by mandrews281** [entech281/Robot2023#237]
Decide based on match time if we can go for the movement points by driving over the charging station and returning.  Needs to be something like:
```

public boolean isTimeForCommunityMove() {
   if ( DriverStation.getMatchTime() < 5.0 ) {
      DriveStation.reportWarning("Moving and Balancing",false):
      return true;
  }
  DriverStation.reportWarning("Time for Balance only",false);
  return false;
}

ConditionalCommand(driveOverAndBalanceCommand, balanceOnlyCommand, this::isTimeForCommunityMove);

```
This probably all belongs in the CommandFactory.

**Comment by dcowden** [comment]
oh, this is a very clever idea!

**Comment by dcowden** [comment]
we also need to run the full center auto routine to see it work-- ideally 3 times in a row.

We can save time still on these areas:
* increase homing move speed
* decrease grippers waits a bit
* move elbow in parallel with beginning to drive

**Comment by mandrews281** [comment]
Done as part of autonomous refactoring.  Note: DriverStation.getMatchTime() returns the time REMAINING in the current game phase so it's a countdown (not a countup) timer.

**Comment by mandrews281** [comment]
done.  works
