### ISSUE TITLE
If you get stuck in the unsafe range, you cant get out again without homing

### ISSUE THREAD

**Issue by dcowden** [entech281/Robot2023#78]

**Comment by dcowden** [comment]
@mandrews281 i think the right fix for this is that we need to allow moving in the direction to clear the condition, not stop everything.

I propose a canMoveUp and canMoveDown method, so that instead of weird stoppage, we dont allow moving in the wrong direction

**Comment by mandrews281** [comment]
I agree that's the best approach.

**Comment by dcowden** [comment]
no longer an issue. we removed the checking logic for  now
