### ISSUE TITLE
Make a homing command that homes both elbow and telecope, IN the right order

### ISSUE THREAD

**Issue by dcowden** [entech281/Robot2023#84]
Currently, this is two commands. 

We want one command, and we want it both on shuffleboard Match tab ( command button), and linked to a button on operator panel/joystick

**Comment by mandrews281** [comment]
Note:  This is a perfect use for the command factory generating a SequentialCommand

**Comment by dcowden** [comment]
this was done by John, but the command needs a better name.

**Comment by dcowden** [comment]
done. the new command appears as homeTelescopeandElbow
