### ISSUE TITLE
Create command to automatically put telescope and elbow at upper , lower scoring, and loading positions

### ISSUE THREAD

**Issue by dcowden** [entech281/Robot2023#85]
Link to button on operator panel.

This is probably the most valuable commands we could make.  This would elminate a lot of human work to get things just right

**Comment by dcowden** [comment]
Need to talk to drivers to see where these are attached: gamepad buttons, operator panel, or joystick

**Comment by dcowden** [comment]
actually just elbow for now

**Comment by dcowden** [comment]
these are created. just need to be bound to the oi selector

**Comment by mandrews281** [comment]
Closing.  The operator panel settings are working for the elbow.
